{"homepages":[],"source_base_path":"E:/documents/Petrik/documents/software/nuclei/nuclei.appdomains/doc/Nuclei.AppDomains.Documentation","xrefmap":"xrefmap.yml","files":[{"type":"Toc","source_relative_path":"obj/api/toc.yml","output":{".html":{"relative_path":"api/toc.html","hash":"QR/4pLL2KES7C+fYFAOyyQ=="}}},{"type":"Conceptual","source_relative_path":"index.md","output":{".html":{"relative_path":"index.html","hash":"JeA/B3YF0QY/Tc/Jp2r3Rw=="}}},{"type":"Toc","source_relative_path":"toc.yml","output":{".html":{"relative_path":"toc.html","hash":"ciE4Dt1DZX2463ewNeaAZw=="}}},{"type":"Conceptual","source_relative_path":"api/index.md","output":{".html":{"relative_path":"api/index.html","hash":"Ct6qpULJsz1b1sXxpN6tdQ=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.AppDomains.Nuclei.ExceptionHandling.ExceptionProcessor.yml","output":{".html":{"relative_path":"api/Nuclei.AppDomains.Nuclei.ExceptionHandling.ExceptionProcessor.html","hash":"/RegIyR6LJGA7tmuOsbcUA=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.AppDomains.Nuclei.ExceptionHandling.yml","output":{".html":{"relative_path":"api/Nuclei.AppDomains.Nuclei.ExceptionHandling.html","hash":"BbW7+nAMaIyUFKjbJR9UFQ=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.AppDomains.Nuclei.ExceptionHandling.ExceptionHandler.yml","output":{".html":{"relative_path":"api/Nuclei.AppDomains.Nuclei.ExceptionHandling.ExceptionHandler.html","hash":"ZLqBEUtjnkzBZSAgHgki9Q=="}}}]}